# Thông tin kết nối Database (Chỉ lưu trên máy cá nhân)
db.url=jdbc:mysql://mysql-123.aivencloud.com:3306/freedb_online_auction?sslMode=REQUIRED
db.username=freedb_admin
db.password=mat_khau_bi_mat_cua_ban