# FILE H??NG D?N C?U HÌNH DATABASE CHO TEAM
# Cách dùng:
# 1. Copy file này và ??i tên b?n copy thành "application.properties"
# 2. ?i?n m?t kh?u ???c cung c?p vào dòng db.password bên d??i và xóa các dòng trên.

db.url=jdbc:mysql://mysql-cdf247b-nguyenvietngocduy2003-5af7.l.aivencloud.com:24276/online_auction?sslMode=REQUIRED&trustServerCertificate=true
db.username=avnadmin
db.password=