package com.auction.shared.protocol;
public enum RequestType {
    LOGIN, LOGOUT, REGISTER,
    GET_USER_PROFILE, UPDATE_USER_PROFILE,
    CREATE_ITEM, GET_ITEM, UPDATE_ITEM, DELETE_ITEM, GET_ALL_ITEMS, SEARCH_ITEM,
    CREATE_AUCTION, GET_AUCTION, GET_ALL_AUCTIONS, PLACE_BID, CLOSE_AUCTION, GET_BID_HISTORY,
    BAN_USER, GET_ALL_USERS,
    SUBSCRIBE_AUCTION
}
