package com.auction.shared.protocol;
public enum RequestType {
    LOGIN, LOGOUT, REGISTER,
    GET_USER_PROFILE, UPDATE_USER_PROFILE,
    CREATE_ITEM, GET_ITEM, UPDATE_ITEM, DELETE_ITEM, GET_ALL_ITEMS, GET_MY_ITEMS, SEARCH_ITEM,
    CREATE_AUCTION, GET_AUCTION, GET_ALL_AUCTIONS, START_AUCTION, PLACE_BID, CLOSE_AUCTION, GET_BID_HISTORY, DELETE_AUCTION,
    BAN_USER, GET_ALL_USERS,
    SUBSCRIBE_AUCTION, SETUP_AUTO_BID, CANCEL_AUTO_BID
}
